# Basics of NumPy Arrays

In [1]:
!pip install numpy

In [2]:
import numpy as np

## Create NumPy arrays and inspect their attributes.

Creating Arrays

In [5]:
# Create a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# Create a 2D array from a nested list
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 3],
                   [7, 8, 9]])
print("\n2D Array:\n", arr_2d)


1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 3]]


Inspecting Array Attributes

In [6]:
# Print the shape, size, and data type of arr_2d
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Data Type:", arr_2d.dtype)


Shape: (2, 3)
Size: 6
Data Type: int64


# Array Creation Techniques
Objective: Explore different ways to create arrays in NumPy.

In [8]:
# Create an array filled with zeros
zeros = np.zeros((3, 3))
print("Zeros:\n", zeros)

# Create an array filled with ones
ones = np.ones((3, 3))
print("\nOnes:\n", ones)

# Create an array with a range of elements
range_array = np.arange(20)
print("\nRange Array:", range_array)
print("\nDtype:",range_array.dtype)
print("Dtype:",zeros.dtype)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Range Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Dtype: int64
Dtype: float64


## Reshaping and Flattening Arrays

Objective: Modify the shape of arrays without changing their data.

In [9]:
# Reshape arr_2d to 3x2
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
reshaped = arr_2d.reshape((3, 2))
print("Reshaped to 3x2:\n", reshaped)

# Flatten arr_2d to a 1D array
flattened = arr_2d.flatten()
print("\nFlattened Array:", flattened)


Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Flattened Array: [1 2 3 4 5 6]


## Concatenating and Splitting Arrays

Objective: Learn to combine and divide arrays.

In [13]:
# Concatenate arr_1d and a new array
arr_3 = np.array([16, 17, 18, 19, 10])
concatenated = np.concatenate([arr_1d, arr_3])
print("Concatenated Array:", concatenated)

# Split concatenated array into three parts
split = np.split(concatenated, [2, 5,8])
print("\nSplit Array:", split)


Concatenated Array: [ 1  2  3  4  5 16 17 18 19 10]

Split Array: [array([1, 2]), array([3, 4, 5]), array([16, 17, 18]), array([19, 10])]


# Linear Algebra and Statistical Operations

## Matrix Operations

Objective: Perform basic linear algebra operations.

In [14]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print("Matrix Product:\n", product)

# Find the determinant of A
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

C = A * B

D = A + B

print(C)
print(D)


Matrix Product:
 [[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004
[[ 5 12]
 [21 32]]
[[ 6  8]
 [10 12]]


## Statistical Analysis

Objective: Apply statistical methods to analyze data.

In [15]:
# Calculate mean, median, and standard deviation
data = np.array([1, 2, 3, 4, 5,5, 6, 7, 8, 9, 10])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance", np.var(data))

# Find unique elements and their counts
unique_elements, counts = np.unique(data, return_counts=True)
print("\nUnique Elements:", unique_elements)
print("Counts:", counts)


Mean: 5.454545454545454
Median: 5.0
Standard Deviation: 2.7423823870906103
Variance 7.520661157024794

Unique Elements: [ 1  2  3  4  5  6  7  8  9 10]
Counts: [1 1 1 1 2 1 1 1 1 1]


## Uniform Distribution

The uniform distribution is perhaps the simplest type of distribution, representing an equal probability of all values in a specified range.

In [ ]:
import numpy as np

# Generate 10 random numbers from a uniform distribution between 0 and 1
uniform_data = np.random.rand(10)

# Generate 10 random numbers from a uniform distribution between 10 and 20
uniform_data_scaled = np.random.uniform(10, 20, 10)

print("Uniform distribution [0, 1):")
print(uniform_data)
print("\nUniform distribution [10, 20):")
print(uniform_data_scaled)


Uniform distribution [0, 1):
[0.61054603 0.69398163 0.78181117 0.34012906 0.33194316 0.49473541
 0.7014058  0.72267783 0.48713573 0.50805104]

Uniform distribution [10, 20):
[18.35005132 13.8311361  16.72291384 16.40058193 10.89350574 17.25282383
 10.19224785 14.59576301 15.38165575 15.31169579]


## Normal (Gaussian) Distribution

The normal distribution is a common continuous probability distribution, often used in the natural and social sciences to represent real-valued random variables whose distributions are not known.

In [ ]:
# Generate 10 random numbers from a normal distribution with mean=0 and std=1
normal_data = np.random.randn(10)

# Generate 10 random numbers from a normal distribution with mean=50 and std=10
normal_data_scaled = np.random.normal(50, 10, 10)

print("Standard normal distribution (mean=0, std=1):")
print(normal_data)
print("\nNormal distribution (mean=50, std=10):")
print(normal_data_scaled)


Standard normal distribution (mean=0, std=1):
[ 0.27878195 -0.13359755  0.76475988  0.4284979  -1.04478382 -2.06997174
  1.05728752 -0.93155364 -0.7014351  -0.20355003]

Normal distribution (mean=50, std=10):
[39.9229263  54.47479338 50.86419886 47.10292516 40.55434365 63.41687737
 33.97963071 54.99913683 56.75814766 56.41128231]


## Binomial Distribution

The binomial distribution represents the number of successes in a sequence of independent experiments.

In [ ]:
# Generate 10 random numbers from a binomial distribution with n=10 and p=0.5
binomial_data = np.random.binomial(n=10, p=0.5, size=10)

print("Binomial distribution (n=10, p=0.5):")
print(binomial_data)


Binomial distribution (n=10, p=0.5):
[4 7 4 3 3 1 2 1 4 4]


## Poisson Distribution
The Poisson distribution is a discrete distribution that expresses the probability of a given number of events occurring in a fixed interval of time or space.

In [ ]:
# Generate 10 random numbers from a Poisson distribution with lambda=3
poisson_data = np.random.poisson(lam=3, size=10)

print("Poisson distribution (lambda=3):")
print(poisson_data)


Poisson distribution (lambda=3):
[5 1 3 3 1 6 4 3 0 2]


## Customizing Random Number Generation
NumPy's random module also supports seeding the random number generator, which can be useful for creating reproducible results during testing or analysis.

In [ ]:
# Seed the random number generator for reproducibility
np.random.seed(42)

# Now, generate random numbers as before
uniform_data_seeded = np.random.rand(5)
print("Uniform distribution with seed (42):")
print(uniform_data_seeded)


Uniform distribution with seed (42):
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


# Show the value of Uniform distribution
take the distribution size as input

then take the range of value from input

a = ?

b = ?

size = ?

In [ ]:
a = int(input("Enter the value of a:"))
b = int(input("Enter the value of b:"))
size = int(input("Enter the value of size:"))

array_1d = np.random.uniform(a,b,size)
print(array_1d)

Enter the value of a:10
Enter the value of b:20
Enter the value of size:10
[14.28344992 17.49710295 19.75644676 19.80431698 15.88880132 10.88801231
 15.03629134 15.7900935  19.0933196  14.25883278]
